packages:
  - '.'

allowBuilds:
  better-sqlite3: true
  sharp: false
  unrs-resolver: false

overrides:
  baseline-browser-mapping: 2.11.0
  browserslist: 4.28.9

minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.5'
  - '@better-auth/drizzle-adapter@1.7.5'
  - '@better-auth/kysely-adapter@1.7.5'
  - '@better-auth/memory-adapter@1.7.5'
  - '@better-auth/mongo-adapter@1.7.5'
  - '@better-auth/prisma-adapter@1.7.5'
  - '@better-auth/telemetry@1.7.5'
  - better-auth@1.7.5
