"""Bounded document metadata and hyperlink inspection."""

from cv_validator.domain import (
    DocumentLink,
    FileDetail,
    FileDetailField,
    FileDetailStatus,
    FileDetails,
    LinkAssociation,
    LinkCheckResult,
    LinkInspection,
    LinkOutcomeStatus,
    LinkReasonCode,
    LinkRole,
    LinkSource,
)

from cv_validator.file_links.catalog import (
    SERVICE_CATALOG_VERSION,
    ServiceDomainMatch,
    classify_service_domain,
    service_entry,
)
from cv_validator.file_links.checker import (
    DNSResolver,
    LinkCheckConfig,
    LinkCheckConfigurationError,
    LinkHTTPResponse,
    LinkHTTPClient,
    LinkInspector,
    LinkNetworkError,
    HttpxLinkHTTPClient,
    SystemDNSResolver,
    inspect_document_links,
)
from cv_validator.file_links.extraction import (
    DOCX_METADATA_EXTRACTOR_VERSION,
    DOCX_HYPERLINK_EXTRACTOR_VERSION,
    PDF_METADATA_EXTRACTOR_VERSION,
    PDF_HYPERLINK_EXTRACTOR_VERSION,
    classify_link_role,
    extract_docx_file_details,
    extract_docx_hyperlinks,
    extract_pdf_file_details,
    extract_pdf_hyperlinks,
    merge_document_links,
)
from cv_validator.file_links.normalization import (
    NormalizedURL,
    URLNormalizationError,
    normalize_url,
    registrable_domain,
    sanitize_url_text,
)

__all__ = [
    "DOCX_METADATA_EXTRACTOR_VERSION",
    "DOCX_HYPERLINK_EXTRACTOR_VERSION",
    "DNSResolver",
    "DocumentLink",
    "FileDetail",
    "FileDetailField",
    "FileDetailStatus",
    "FileDetails",
    "LinkAssociation",
    "LinkCheckConfig",
    "LinkCheckConfigurationError",
    "LinkCheckResult",
    "LinkHTTPResponse",
    "LinkHTTPClient",
    "LinkInspector",
    "LinkInspection",
    "LinkNetworkError",
    "LinkOutcomeStatus",
    "LinkReasonCode",
    "LinkRole",
    "LinkSource",
    "NormalizedURL",
    "PDF_METADATA_EXTRACTOR_VERSION",
    "PDF_HYPERLINK_EXTRACTOR_VERSION",
    "SERVICE_CATALOG_VERSION",
    "ServiceDomainMatch",
    "SystemDNSResolver",
    "HttpxLinkHTTPClient",
    "URLNormalizationError",
    "classify_service_domain",
    "classify_link_role",
    "service_entry",
    "extract_docx_file_details",
    "extract_docx_hyperlinks",
    "extract_pdf_file_details",
    "extract_pdf_hyperlinks",
    "inspect_document_links",
    "merge_document_links",
    "normalize_url",
    "registrable_domain",
    "sanitize_url_text",
]
